[project]
name = "python-testing-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.11.0",
    "pytest>=9.0.1",
]

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
